### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by aneppew** [Dipeshpal/Jarvis-Assisant#18]
`Traceback (most recent call last):
  File "C:\Users\anep\PycharmProjects\David\David.py", line 144, in <module>
    start()
  File "C:\Users\anep\PycharmProjects\David\David.py", line 28, in start
    response = obj.mic_input()
  File "C:\Users\anep\AppData\Local\Programs\Python\Python39\lib\site-packages\JarvisAI\__init__.py", line 147, in mic_input
    user_name = res['data']['name_']
TypeError: 'NoneType' object is not subscriptable
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-m8us58q4\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
`

**Comment by Dipeshpal** [comment]
read docs
